server {
    listen 80;
    server_name homesystem.local;

    location / {
        proxy_pass http://drink_api_prod:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /metrics {
        allow 192.168.1.50;
        deny all;
        proxy_pass http://drink_api_prod:5001/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}