server {
    listen 80;
    server_name staging.local;

    location / {
        proxy_pass http://drink_api_staging:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /metrics {
        allow 192.168.1.50;
        deny all;
        proxy_pass http://drink_api_staging:5002/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}