events {}

http {
    server {
        listen 80;
        server_name staging.local;

        location / {
            proxy_pass http://drink_api_staging:5002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}